graph = {
    'Addis Ababa': ['Adama', 'Ambo', 'Debre Birhan'],
    'Ambo': ['Addis Ababa', 'Wolkite', 'Nekemte'],
    'Nekemte': ['Ambo', 'Bedele', 'Gimbi'],
    'Gimbi': ['Nekemte', 'Dembi Dollo'],
    'Dembi Dollo': ['Gambela', 'Assosa', 'Gimbi'],
    'Gambela': ['Dembi Dollo', 'Gore'],
    'Gore': ['Gambela', 'Tepi', 'Bedele'],
    'Tepi': ['Gore', 'Bonga', 'Mizan Teferi'],
    'Mizan Teferi': ['Tepi', 'Bonga'],
    'Bonga': ['Mizan Teferi', 'Tepi', 'Dawro', 'Jimma'],
    'Dawro': ['Bonga', 'Wolaita sodo'],
    'Wolaita sodo': ['Dawro', 'Arba Minch', 'Hossana'],
    'Arba Minch': ['Wolaita sodo', 'Basketo', 'Konso'],
    'Basketo': ['Arba Minch', 'Bench Maji'],
    'Hossana': ['Wolaita sodo', 'Shashemene', 'Worabe'],
    'Worabe': ['Hossana', 'Wolkite', 'Butta Jira'],
    'Wolkite': ['Worabe', 'Ambo', 'Jimma'],
    'Butta Jira': ['Worabe', 'Batu'],
    'Batu': ['Butta Jira', 'Shashemene', 'Adama'],
    'Adama': ['Batu', 'Addis Ababa', 'Matahara', 'Assela'],
    'Assela': ['Adama', 'Assasa'],
    'Assasa': ['Assela', 'Dodolla'],
    'Dodolla': ['Shashemene', 'Bale', 'Assasa'],
    'Shashemene': ['Dodolla', 'Hawassa', 'Batu', 'Hossana'],
    'Hawassa': ['Shashemene', 'Dilla'],
    'Matahara': ['Adama', 'Awash'],
    'Awash': ['Matahara', 'Chiro', 'Gambi Rasu'],
    'Chiro': ['Awash', 'Dire Dawa'],
    'Dire Dawa': ['Chiro', 'Harar'],
    'Gambi Rasu': ['Awash', 'Samara'],
    'Samara': ['Gambi Rasu', 'Woldia', 'Alamata', 'Fanti Rasu'],
    'Fanti Rasu': ['Samara', 'Kilbet Rasu'],
    'Woldia': ['Samara', 'Lalibela', 'Alamata', 'Dessie'],
    'Dessie': ['Woldia', 'Kemise'],
    'Kemise': ['Dessie', 'Debre Sina'],
    'Debre Sina': ['Kemise', 'Debre Birhan', 'Debre Markos'],
    'Debre Birhan': ['Addis Ababa', 'Debre Sina'],
    'Debre Markos': ['Debre Sina', 'Finote Selam'],
    'Finote Selam': ['Debre Markos', 'Bahir Dar', 'Injibara'],
    'Injibara': ['Finote Selam', 'Bahir Dar'],
    'Bahir Dar': ['Injibara', 'Finote Selam', 'Metekel', 'Azezo', 'Debre Tabor'],
    'Azezo': ['Bahir Dar', 'Gondar', 'Metema'],
    'Metema': ['Azezo', 'Gondar', 'Kartum'],
    'Gondar': ['Azezo', 'Metema', 'Debark', 'Humera'],
    'Debark': ['Gondar', 'Shire'],
    'Shire': ['Debark', 'Humera', 'Axum'],
    'Axum': ['Shire', 'Adwa', 'Asmara'],
    'Debre Tabor': ['Bahir Dar', 'Lalibela'],
    'Lalibela': ['Debre Tabor', 'Woldia', 'Sekota'],
    'Sekota': ['Lalibela', 'Alamata', 'Mekele'],
    'Alamata': ['Sekota', 'Woldia', 'Samara', 'Mekele'],
    'Mekele': ['Alamata', 'Sekota', 'Adwa', 'Adigrat'],
    'Adwa': ['Mekele', 'Axum', 'Adigrat'],
    'Adigrat': ['Mekele', 'Asmera', 'Adwa'],
    'Metekel': ['Bahir Dar'],
    'Dilla': ['Hawassa', 'Bule Hora'],
    'Bule Hora': ['Dilla', 'Yabello'],
    'Yabello': ['Bule Hora', 'Konso', 'Moyale'],
    'Konso': ['Yabello', 'Arba Minch'],
    'Bale': ['Dodolla', 'Goba', 'Liben', 'Sof Oumer'],
    'Sof Oumer': ['Bale', 'Goba', 'Gode'],
    'Gode': ['Sof Oumer', 'Kebri Dehar', 'Dollo', 'Mokadisho'],
    'Kebri Dehar': ['Gode', 'Werder', 'Dega Habur'],
    'Dega Habur': ['Kebri Dehar', 'Jijiga'],
    'Jijiga': ['Dega Habur', 'Babile'],
    'Babile': ['Jijiga', 'Harar', 'Goba'],
    'Harar': ['Dire Dawa', 'Babile'],
    'Goba': ['Bale', 'Babile', 'Sof Oumer'],
    'Jimma': ['Bonga', 'Wolkite', 'Bedele'],
    'Bench Maji': ['Basketo', 'Juba'],
    'Dollo': ['Gode'],
    'Liben': ['Bale'],
    'Moyale': ['Yabello', 'Nairobi'],
    'Bedele': ['Nekemte', 'Jimma', 'Gore'],
    'Humera': ['Gondar', 'Shire', 'Kartum'],
    'Kilbet Rasu': ['Fanti Rasu'],
    'Werder': ['Kebri Dehar'],
}